### model
model_name_or_path: your_path
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
#lora_target: "q_proj,k_proj,v_proj,o_proj" 
max_grad_norm: 1.0
lora_alpha: 16
lora_dropout: 0.05
lora_rank: 8
# lora_target: all

### dataset
dataset: keyphrase_patent_zh_A
template: qwen
cutoff_len: 4000
max_samples: 3100
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4

### output
output_dir: your_path
logging_steps: 50
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.01
bf16: true
flash_attn: disabled
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
